name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          ref: master
      - name: Setup Node.js with GitHub Package Registry
        uses: actions/setup-node@v1
        with:
          node-version: 12
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          registry-url: 'https://npm.pkg.github.com'
          scope: 'oleg-koval'
          always-auth: true
      - name: Install dependencies
        run:
          npm ci --ignore-scripts --no-audit --prefer-offline --progress=false
      - name: Test run
        uses: ridedott/semantic-release-action@test-dist-install
        env:
          # This must be used as GitHub Actions token does not support pushing
          # to protected branches.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_WORKAROUND }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          DRY_RUN: false
          DEBUG: true
          SCRIPT_PATH: ./scripts/say-hello.sh
