name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history.
          fetch-depth: 0
          persist-credentials: false
      - name: Release
        uses: ridedott/semantic-release-action@master
        env:
          # Use an automatically populated `GITHUB_TOKEN` environment
          # variable.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # `GITHUB_TOKEN` can also be used to authenticate with GitHub
          # Packages.
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: true
          SCRIPT_PATH: /test-script/say_hello.sh
