name: Continuous Delivery

on:
  push:
    branches:
      - master
      - "beta"
      - "alpha"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history.
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          key: npm-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies test
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_WORKAROUND }}
        name: Release
        id: build_package
        uses: ridedott/release-me-action@master
        with:
          node-module: true
          release-branches: '["master", {"channel":"alpha","prerelease":true, "name": "alpha" }, {"channel":"beta","prerelease":false, "name": "beta" }]'
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          registry-url: "https://npm.pkg.github.com"
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN_WORKAROUND }}
        name: Publish to GitHub Packages
        run: npm publish

      - name: output
        run: |
          echo ${{ steps.build_package.outputs.version }} : ${{ steps.build_package.outputs.type }}
          echo ${{ steps.build_package.outputs.status }}
          echo ${{ steps.build_package.outputs.released }}

      - name: check output true
        if: steps.build_package.outputs.released == 'true'
        run: |
          echo ALL GOOD!!!

      - name: check output false
        if: steps.build_package.outputs.released == 'false'
        run: |
          echo ALL BAD!!!
